import { NextRequest, NextResponse } from "next/server";
import { getServerSupabase } from "@/lib/supabase/server";
import { checkRateLimit } from "@/lib/security/rateLimiter";
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export async function GET(req:NextRequest,{params}:{params:{id:string}}){
  if(!UUID.test(params.id))return NextResponse.json({error:"Album not found"},{status:404}); const client=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown"; if(!checkRateLimit(`public-album:${client.slice(0,80)}`,120,60).allowed)return NextResponse.json({error:"Too many requests"},{status:429});
  const db=getServerSupabase(); if(!db)return NextResponse.json({error:"Album unavailable"},{status:503}); const {data:album,error}=await db.from("media_albums").select("id,owner_id,title,description,category,tags,cover_media_id,published_at,created_at").eq("id",params.id).eq("visibility","PUBLIC").eq("moderation_status","APPROVED").maybeSingle(); if(error||!album)return NextResponse.json({error:"Album not found"},{status:404});
  const {data:owner}=await db.from("profiles").select("id,display_name,username,verification_status,verification_level").eq("id",album.owner_id).eq("profile_visibility","EVERYONE").eq("public_profile_visibility",true).eq("account_status","ACTIVE").eq("discovery_disabled",false).maybeSingle(); if(!owner)return NextResponse.json({error:"Album not found"},{status:404});
  const {data:links}=await db.from("media_album_items").select("media_id,sort_order").eq("album_id",album.id).order("sort_order",{ascending:true}); const mediaIds=(links||[]).map((link)=>link.media_id); const {data:media}=mediaIds.length?await db.from("media_objects").select("id,title,description,mime_type").in("id",mediaIds).eq("owner_id",album.owner_id).eq("media_type","IMAGE").eq("visibility","PUBLIC").eq("upload_status","AVAILABLE").eq("processing_status","READY").eq("moderation_status","APPROVED"):{data:[]}; const mediaMap=new Map((media||[]).map((item)=>[item.id,item]));
  const photos=(links||[]).flatMap((link)=>{const item=mediaMap.get(link.media_id);return item?[{id:item.id,title:item.title||"Album photo",description:item.description||null,mimeType:item.mime_type,url:`/api/public/media/${item.id}`}]:[];});
  return NextResponse.json({album:{id:album.id,title:album.title,description:album.description,category:album.category,tags:Array.isArray(album.tags)?album.tags.slice(0,20):[],publishedAt:album.published_at||album.created_at,owner:{id:owner.id,displayName:owner.display_name||owner.username||"Intimo member",verified:owner.verification_status==="VERIFIED"||["LEVEL_3_PROFILE_BIOMETRIC","LEVEL_4_CREATOR"].includes(owner.verification_level||"")},photos}},{headers:{"Cache-Control":"public, max-age=30, stale-while-revalidate=120"}});
}
