import { Profile, Conversation, VerificationRequest, ReportItem, NotificationItem } from "@/types";

export const MOCK_PROFILES: Profile[] = [
  {
    id: "prof-1",
    userId: "user-1",
    displayName: "Elena Vance",
    dateOfBirth: "2000-04-12",
    age: 26,
    gender: "FEMALE",
    sexualOrientation: "BISEXUAL",
    country: "Monaco",
    city: "Monte Carlo",
    location: "Monaco / London",
    languages: ["English", "French", "Italian"],
    headline: "Art Curator & High-Discretion Private Hostess",
    bio: "Art curator, wine enthusiast & private event hostess. Looking for high-discretion connections and exclusive dining experiences across Europe.",
    interests: ["Contemporary Art", "Fine Wine", "Private Aviation", "Yachting"],
    lifestyleTags: ["Luxury Lifestyle", "Gourmet Dining", "VIP Social Club"],
    hobbies: ["Classical Piano", "Polo", "Vintage Champagne Tasting"],
    relationshipStatus: "SINGLE",
    lookingFor: ["Dating", "Casual Connection", "Social Events", "Travel Partner"],
    isCoupleProfile: false,

    publicProfileVisibility: true,
    photoVisibilityDefault: "PUBLIC",
    locationPrecision: "CITY",
    showOnlineStatus: true,
    showDistance: true,
    allowDirectMessages: true,
    requireVerificationToMessage: false,

    verified: true,
    isOnline: true,
    distanceKm: 4,
    compatibilityScore: 95,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      {
        id: "m-1",
        url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PUBLIC",
        sortOrder: 1,
        isProfilePhoto: true,
      },
      {
        id: "m-2",
        url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PRIVATE_MEMBERS",
        sortOrder: 2,
      },
      {
        id: "m-3",
        url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "FAVORITES_ONLY",
        price: 25,
        title: "Exclusive Private Lounge Album",
        sortOrder: 3,
      },
    ],
  },
  {
    id: "prof-2",
    userId: "user-2",
    displayName: "Julian & Sophia",
    dateOfBirth: "1994-08-20",
    age: 32,
    gender: "COUPLE_MF",
    sexualOrientation: "BISEXUAL",
    country: "Switzerland",
    city: "Zurich",
    location: "Zurich / Paris",
    languages: ["German", "English", "French"],
    headline: "Bi-Curious Power Couple Hosting Private Dinners",
    bio: "Sophisticated bi-curious couple enjoying the high life. We host private dinners and seek like-minded individuals or elegant couples for memorable evenings.",
    interests: ["Architectural Design", "Mixology", "Wellness Retreats", "High Fashion"],
    lifestyleTags: ["Couples Lifestyle", "Mixology", "Luxury Architecture"],
    hobbies: ["Private Wine Cellars", "Skiing St. Moritz", "Contemporary Art Collecting"],
    relationshipStatus: "COUPLE",
    lookingFor: ["Couples", "Casual Connection", "Social Events"],
    isCoupleProfile: true,
    partnerDisplayName: "Sophia",
    partnerAge: 29,
    partnerGender: "FEMALE",

    publicProfileVisibility: true,
    photoVisibilityDefault: "PUBLIC",
    locationPrecision: "CITY",
    showOnlineStatus: true,
    showDistance: true,
    allowDirectMessages: true,
    requireVerificationToMessage: true,

    verified: true,
    isOnline: false,
    distanceKm: 12,
    compatibilityScore: 88,
    avatarUrl: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      {
        id: "m-4",
        url: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PUBLIC",
        sortOrder: 1,
        isProfilePhoto: true,
      },
      {
        id: "m-5",
        url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PRIVATE_MEMBERS",
        sortOrder: 2,
      },
    ],
  },
  {
    id: "prof-3",
    userId: "user-3",
    displayName: "Aria Thorne",
    dateOfBirth: "2002-02-14",
    age: 24,
    gender: "FEMALE",
    sexualOrientation: "PANSEXUAL",
    country: "Switzerland",
    city: "Geneva",
    location: "Geneva / London",
    languages: ["English", "French"],
    headline: "Classical Violinist & Exclusive Video Content Creator",
    bio: "Luxury lifestyle creator & classical violinist. Monthly exclusive video journals, behind-the-scenes performances, and live streaming once a week.",
    interests: ["Classical Music", "High Jewelry", "Luxury Travel", "Photography"],
    lifestyleTags: ["Creator Economy", "VIP Performances", "Travel Journals"],
    hobbies: ["Violin Recitals", "High Jewelry Design", "Private Jet Travel"],
    relationshipStatus: "OPEN_RELATIONSHIP",
    lookingFor: ["Creator Followers", "Online Interaction", "Friendship"],
    isCoupleProfile: false,

    publicProfileVisibility: true,
    photoVisibilityDefault: "PUBLIC",
    locationPrecision: "CITY",
    showOnlineStatus: true,
    showDistance: false,
    allowDirectMessages: true,
    requireVerificationToMessage: false,

    verified: true,
    isOnline: true,
    compatibilityScore: 92,
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      {
        id: "m-6",
        url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PUBLIC",
        sortOrder: 1,
        isProfilePhoto: true,
      },
      {
        id: "m-7",
        url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PAID_PER_VIEW",
        price: 49.99,
        title: "Exclusive Private Violin Session Video",
        sortOrder: 2,
      },
    ],
  },
  {
    id: "prof-4",
    userId: "user-4",
    displayName: "Alexander Sterling",
    dateOfBirth: "1991-11-05",
    age: 35,
    gender: "MALE",
    sexualOrientation: "HETEROSEXUAL",
    country: "United Kingdom",
    city: "London",
    location: "London / Mayfair",
    languages: ["English"],
    headline: "Tech Founder & Fine Watch Collector",
    bio: "Venture capitalist, tech founder, and avid watch collector. Seeking a charming companion for black-tie galas and private weekend escapes.",
    interests: ["Horology", "Venture Capital", "Polo", "Fine Dining"],
    lifestyleTags: ["Venture Capital", "Black Tie Galas", "Supercars"],
    hobbies: ["Watch Auctions", "Polo Tournaments", "Private Dining"],
    relationshipStatus: "SINGLE",
    lookingFor: ["Dating", "Social Events", "Travel Partner"],
    isCoupleProfile: false,

    publicProfileVisibility: true,
    photoVisibilityDefault: "PUBLIC",
    locationPrecision: "CITY",
    showOnlineStatus: true,
    showDistance: true,
    allowDirectMessages: true,
    requireVerificationToMessage: true,

    verified: true,
    isOnline: false,
    distanceKm: 8,
    compatibilityScore: 84,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      {
        id: "m-8",
        url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PUBLIC",
        sortOrder: 1,
        isProfilePhoto: true,
      },
    ],
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    userId: "usr-demo-1",
    type: "PROFILE_VIEW",
    title: "Profile Impression",
    message: "Julian & Sophia viewed your profile.",
    actorName: "Julian & Sophia",
    actorAvatar: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
    targetLink: "/profile/prof-2",
    isRead: false,
    createdAt: "10 mins ago",
  },
  {
    id: "notif-2",
    userId: "usr-demo-1",
    type: "FAVORITED",
    title: "Saved to Favorites",
    message: "Alexander Sterling saved you to their favorites list.",
    actorName: "Alexander Sterling",
    actorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
    targetLink: "/profile/prof-4",
    isRead: false,
    createdAt: "1 hour ago",
  },
  {
    id: "notif-3",
    userId: "usr-demo-1",
    type: "VERIFICATION_APPROVED",
    title: "100% ID Verified",
    message: "Your biometric adult verification request was approved by compliance team.",
    isRead: true,
    createdAt: "Yesterday",
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    participant: MOCK_PROFILES[0],
    lastMessage: {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "prof-1",
      senderName: "Elena Vance",
      senderAvatar: MOCK_PROFILES[0].avatarUrl,
      content: "I'll be visiting London next Thursday. Shall we meet at the Connaught Bar?",
      createdAt: "10:42 AM",
    },
    unreadCount: 1,
    updatedAt: "10:42 AM",
  },
  {
    id: "conv-2",
    participant: MOCK_PROFILES[1],
    lastMessage: {
      id: "msg-2",
      conversationId: "conv-2",
      senderId: "user-current",
      senderName: "You",
      senderAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=800&q=80",
      content: "Thank you for the invitation! We would love to join your private tasting.",
      createdAt: "Yesterday",
    },
    unreadCount: 0,
    updatedAt: "Yesterday",
  },
];

export const MOCK_VERIFICATION_REQUESTS: VerificationRequest[] = [
  {
    id: "verif-101",
    user: {
      id: "usr-88",
      username: "seraphina_v",
      email: "seraphina@velora.club",
      role: "CREATOR",
    },
    idDocumentUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80",
    selfieWithNoteUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
    submittedAt: "2026-08-02 14:30",
    status: "PENDING",
  },
  {
    id: "verif-102",
    user: {
      id: "usr-89",
      username: "marcus_monaco",
      email: "marcus@luxury.mc",
      role: "MEMBER",
    },
    idDocumentUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80",
    selfieWithNoteUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80",
    submittedAt: "2026-08-03 06:15",
    status: "PENDING",
  },
];

export const MOCK_REPORTS: ReportItem[] = [
  {
    id: "rep-1",
    reporterUsername: "elena_vance",
    reportedUsername: "fake_user_99",
    reportedUserRole: "MEMBER",
    reason: "UNDERAGE_SUSPICION",
    details: "User posted media that raises age verification concerns. Requesting immediate verification audit.",
    status: "PENDING",
    submittedAt: "2026-08-02 18:00",
  },
  {
    id: "rep-2",
    reporterUsername: "julian_sophia",
    reportedUsername: "spammer_bot",
    reportedUserRole: "MEMBER",
    reason: "SPAM_SOLICITATION",
    details: "Sent automated link redirecting to third-party website.",
    status: "PENDING",
    submittedAt: "2026-08-03 01:20",
  },
];
