import {
  Profile,
  Conversation,
  VerificationRequest,
  ReportItem,
  NotificationItem,
  ModerationLog,
  UserSafetySettings,
  ContentAlbum,
  ContentVideo,
  CreatorApplication,
  PaymentTransaction,
  PayoutRequest,
  RefundItem,
  WalletInfo,
  LiveStream,
  LiveChatMessage,
} from "@/types";

export const CREATOR_CATEGORIES = [
  "Contemporary Art",
  "Classical Music",
  "VIP Lifestyle",
  "High Fashion",
  "Private Aviation",
  "Gourmet & Wine",
  "Luxury Fitness",
  "Couples Lifestyle",
];

export const MOCK_WALLET: WalletInfo = {
  id: "w-demo-1",
  userId: "usr-demo-1",
  availableBalance: 420.50,
  pendingBalance: 150.00,
  currency: "USD",
};

export const MOCK_LIVE_STREAMS: LiveStream[] = [
  {
    id: "ls-1",
    creatorId: "prof-3",
    creatorName: "Aria Thorne",
    creatorAvatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    title: "Geneva Alpine Residence - Private Evening Solo Concert",
    description: "Exclusive live 4K WebRTC stream performing Paganini & Bach from a private chalet in the Swiss Alps.",
    category: "Classical Music",
    thumbnailUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    accessType: "TICKETED_PPV",
    ticketPrice: 20.00,
    status: "LIVE",
    scheduledStartTime: "Live Now",
    durationMinutes: 90,
    currentViewersCount: 242,
    peakViewersCount: 310,
    totalRevenue: 4840.00,
    streamUrl: "https://assets.mixkit.co/videos/preview/mixkit-classical-violinist-performing-41584-large.mp4",
    createdAt: "1 hour ago",
  },
  {
    id: "ls-2",
    creatorId: "prof-1",
    creatorName: "Elena Vance",
    creatorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    title: "Monte Carlo Yacht Salon - Private Art Auction Preview",
    description: "Live walkthrough of contemporary rare pieces before tomorrow's private auction.",
    category: "Contemporary Art",
    thumbnailUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    accessType: "SUBSCRIBER_ONLY",
    ticketPrice: 0,
    status: "SCHEDULED",
    scheduledStartTime: "Tonight, 9:00 PM CET",
    durationMinutes: 60,
    currentViewersCount: 0,
    peakViewersCount: 0,
    totalRevenue: 0,
    createdAt: "3 hours ago",
  },
];

export const MOCK_LIVE_CHAT: LiveChatMessage[] = [
  {
    id: "lc-1",
    streamId: "ls-1",
    senderName: "Julian & Sophia",
    senderAvatar: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
    content: "Breathtaking acoustics! Enjoying this from Zurich.",
    createdAt: "10:32 AM",
  },
  {
    id: "lc-2",
    streamId: "ls-1",
    senderName: "Elena Vance",
    senderAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    content: "Tipped $50.00: \"Sublime Bach performance Aria!\"",
    isTipMessage: true,
    tipAmount: 50.00,
    createdAt: "10:35 AM",
  },
];

export const MOCK_TRANSACTIONS: PaymentTransaction[] = [
  {
    id: "tx-101",
    buyerUsername: "elena_vance",
    sellerUsername: "aria_thorne",
    productTitle: "Violin Solo Performance - Private Salon Concert Ticket",
    grossAmount: 20.00,
    platformCut: 3.00,
    creatorEarnings: 16.00,
    taxAmount: 1.00,
    currency: "USD",
    type: "LIVE_EXPERIENCE_TICKET",
    status: "COMPLETED",
    provider: "VELORA_WALLET",
    createdAt: "10:30 AM",
  },
];

export const MOCK_PAYOUT_REQUESTS: PayoutRequest[] = [
  {
    id: "po-1",
    username: "aria_thorne",
    amount: 1450.00,
    currency: "USD",
    payoutMethod: "SEPA Direct Bank Transfer",
    payoutDetails: "CH93 0000 0000 0000 0000 0",
    status: "PENDING",
    requestedAt: "2026-08-02 18:30",
  },
];

export const MOCK_REFUND_REQUESTS: RefundItem[] = [
  {
    id: "ref-1",
    username: "disappointed_member",
    productTitle: "Private Photo Unlock",
    amount: 25.00,
    reason: "Media file preview did not load due to connection timeout.",
    status: "PENDING",
    requestedAt: "2026-08-03 02:10",
  },
];

export const MOCK_PROFILES: Profile[] = [
  {
    id: "prof-1",
    userId: "user-1",
    displayName: "Elena Vance",
    dateOfBirth: "2000-04-12",
    age: 26,
    gender: "FEMALE",
    sexualOrientation: "BISEXUAL",
    country: "Monaco",
    city: "Monte Carlo",
    location: "Monaco / London",
    languages: ["English", "French", "Italian"],
    headline: "Art Curator & High-Discretion Private Hostess",
    bio: "Art curator, wine enthusiast & private event hostess. Looking for high-discretion connections and exclusive dining experiences across Europe.",
    interests: ["Contemporary Art", "Fine Wine", "Private Aviation", "Yachting"],
    lifestyleTags: ["Luxury Lifestyle", "Gourmet Dining", "VIP Social Club"],
    hobbies: ["Classical Piano", "Polo", "Vintage Champagne Tasting"],
    relationshipStatus: "SINGLE",
    lookingFor: ["Dating", "Casual Connection", "Social Events", "Travel Partner"],
    isCoupleProfile: false,

    categories: ["Contemporary Art", "VIP Lifestyle"],
    monthlySubscriptionPrice: 24.99,
    followersCount: 1420,
    subscribersCount: 185,
    totalContentCount: 24,

    publicProfileVisibility: true,
    photoVisibilityDefault: "PUBLIC",
    locationPrecision: "CITY",
    showOnlineStatus: true,
    showDistance: true,
    allowDirectMessages: true,
    requireVerificationToMessage: false,

    verified: true,
    verificationLevel: "LEVEL_4_CREATOR",
    isOnline: true,
    distanceKm: 4,
    compatibilityScore: 95,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [],
  },
  {
    id: "prof-2",
    userId: "user-2",
    displayName: "Julian & Sophia",
    dateOfBirth: "1994-08-20",
    age: 32,
    gender: "COUPLE_MF",
    sexualOrientation: "BISEXUAL",
    country: "Switzerland",
    city: "Zurich",
    location: "Zurich / Paris",
    languages: ["German", "English", "French"],
    headline: "Bi-Curious Power Couple Hosting Private Dinners",
    bio: "Sophisticated bi-curious couple enjoying the high life. We host private dinners and seek like-minded individuals or elegant couples for memorable evenings.",
    interests: ["Architectural Design", "Mixology", "Wellness Retreats", "High Fashion"],
    lifestyleTags: ["Couples Lifestyle", "Mixology", "Luxury Architecture"],
    hobbies: ["Private Wine Cellars", "Skiing St. Moritz", "Contemporary Art Collecting"],
    relationshipStatus: "COUPLE",
    lookingFor: ["Couples", "Casual Connection", "Social Events"],
    isCoupleProfile: true,
    partnerDisplayName: "Sophia",
    partnerAge: 29,
    partnerGender: "FEMALE",

    categories: ["Couples Lifestyle", "Gourmet & Wine"],
    monthlySubscriptionPrice: 34.99,
    followersCount: 890,
    subscribersCount: 94,
    totalContentCount: 16,

    publicProfileVisibility: true,
    photoVisibilityDefault: "PUBLIC",
    locationPrecision: "CITY",
    showOnlineStatus: true,
    showDistance: true,
    allowDirectMessages: true,
    requireVerificationToMessage: true,

    verified: true,
    verificationLevel: "LEVEL_3_PROFILE_BIOMETRIC",
    isOnline: false,
    distanceKm: 12,
    compatibilityScore: 88,
    avatarUrl: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [],
  },
  {
    id: "prof-3",
    userId: "user-3",
    displayName: "Aria Thorne",
    dateOfBirth: "2002-02-14",
    age: 24,
    gender: "FEMALE",
    sexualOrientation: "PANSEXUAL",
    country: "Switzerland",
    city: "Geneva",
    location: "Geneva / London",
    languages: ["English", "French"],
    headline: "Classical Violinist & Exclusive Video Content Creator",
    bio: "Luxury lifestyle creator & classical violinist. Monthly exclusive video journals, behind-the-scenes performances, and live streaming once a week.",
    interests: ["Classical Music", "High Jewelry", "Luxury Travel", "Photography"],
    lifestyleTags: ["Creator Economy", "VIP Performances", "Travel Journals"],
    hobbies: ["Violin Recitals", "High Jewelry Design", "Private Jet Travel"],
    relationshipStatus: "OPEN_RELATIONSHIP",
    lookingFor: ["Creator Followers", "Online Interaction", "Friendship"],
    isCoupleProfile: false,

    categories: ["Classical Music", "High Fashion"],
    monthlySubscriptionPrice: 19.99,
    followersCount: 3820,
    subscribersCount: 450,
    totalContentCount: 42,

    publicProfileVisibility: true,
    photoVisibilityDefault: "PUBLIC",
    locationPrecision: "CITY",
    showOnlineStatus: true,
    showDistance: false,
    allowDirectMessages: true,
    requireVerificationToMessage: false,

    verified: true,
    verificationLevel: "LEVEL_4_CREATOR",
    isOnline: true,
    compatibilityScore: 92,
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [],
  },
];

export const MOCK_CREATOR_ALBUMS: ContentAlbum[] = [
  {
    id: "alb-1",
    creatorId: "prof-1",
    creatorName: "Elena Vance",
    creatorAvatar: MOCK_PROFILES[0].avatarUrl,
    title: "Monaco Art Fair Private Gala Suite",
    description: "Exclusive photos from behind the velvet ropes at the Monte Carlo Private Lounge Gala.",
    category: "Contemporary Art",
    previewImages: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    ],
    lockedImages: [],
    price: 25.0,
    visibility: "PAID_PER_VIEW",
    publicationStatus: "PUBLISHED",
    totalPhotosCount: 18,
    createdAt: "2 days ago",
  },
];

export const MOCK_CREATOR_VIDEOS: ContentVideo[] = [
  {
    id: "vid-1",
    creatorId: "prof-3",
    creatorName: "Aria Thorne",
    creatorAvatar: MOCK_PROFILES[2].avatarUrl,
    title: "Violin Solo Performance - Private Salon Concert",
    description: "4K 60fps recording of Bach Partita performed in a private Alpine residence.",
    category: "Classical Music",
    previewThumbnail: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80",
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-classical-violinist-performing-41584-large.mp4",
    durationSeconds: 420,
    price: 35.0,
    visibility: "PAID_PER_VIEW",
    publicationStatus: "PUBLISHED",
    createdAt: "1 week ago",
  },
];

export const MOCK_CREATOR_APPLICATIONS: CreatorApplication[] = [
  {
    id: "capp-1",
    user: {
      id: "user-88",
      username: "seraphina_v",
      email: "seraphina@velora.club",
    },
    categories: ["High Fashion", "VIP Lifestyle"],
    proposedMonthlyPrice: 29.99,
    bio: "High fashion model and luxury host based in Paris. Creating weekly couture lookbooks & private dinner diaries.",
    payoutMethod: "SEPA Direct Bank Transfer",
    payoutDetails: "IBAN CH93 0000 0000 0000 0000 0",
    status: "PENDING",
    submittedAt: "2026-08-02 16:45",
  },
];

export const MOCK_SAFETY_SETTINGS: UserSafetySettings = {
  whoCanMessageMe: "EVERYONE",
  allowPhotoMessages: true,
  allowRequestsFromUnknown: true,
  enableMessageFiltering: true,
  profileVisibilitySetting: "MEMBERS_ONLY",
  hideLastActive: false,
  appearInSearch: true,
  dailyMessageLimit: 50,
  messagesSentToday: 4,
};

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    participant: MOCK_PROFILES[0],
    lastMessage: {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "prof-1",
      senderName: "Elena Vance",
      senderAvatar: MOCK_PROFILES[0].avatarUrl,
      content: "I'll be visiting London next Thursday. Shall we meet at the Connaught Bar?",
      status: "READ",
      createdAt: "10:42 AM",
    },
    unreadCount: 1,
    updatedAt: "10:42 AM",
    isTyping: true,
  },
];

export const MOCK_VERIFICATION_REQUESTS: VerificationRequest[] = [];
export const MOCK_REPORTS: ReportItem[] = [];
export const MOCK_MODERATION_LOGS: ModerationLog[] = [];
export const MOCK_NOTIFICATIONS: NotificationItem[] = [];
