import { Profile, Conversation, VerificationRequest, ReportItem } from "@/types";

export const MOCK_PROFILES: Profile[] = [
  {
    id: "prof-1",
    userId: "user-1",
    displayName: "Elena Vance",
    age: 26,
    gender: "FEMALE",
    sexualOrientation: "BISEXUAL",
    location: "Monaco / London",
    bio: "Art curator, wine enthusiast & private event hostess. Looking for high-discretion connections and exclusive dining experiences across Europe.",
    interests: ["Contemporary Art", "Fine Wine", "Private Aviation", "Yachting"],
    relationshipStatus: "SINGLE",
    lookingFor: ["Discreet Connections", "Fine Dining", "Travel Partner"],
    isCoupleProfile: false,
    showOnlineStatus: true,
    showDistance: true,
    allowDirectMessages: true,
    requireVerificationToMessage: false,
    verified: true,
    isOnline: true,
    distanceKm: 4,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      {
        id: "m-1",
        url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PUBLIC",
        isProfilePhoto: true,
      },
      {
        id: "m-2",
        url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PRIVATE_MEMBERS",
      },
      {
        id: "m-3",
        url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "SUBSCRIBERS_ONLY",
        price: 25,
        title: "Exclusive Private Lounge Album",
      },
    ],
  },
  {
    id: "prof-2",
    userId: "user-2",
    displayName: "Julian & Sophia",
    age: 32,
    gender: "COUPLE_MF",
    sexualOrientation: "BISEXUAL",
    location: "Zurich / Paris",
    bio: "Sophisticated bi-curious couple enjoying the high life. We host private dinners and seek like-minded individuals or elegant couples for memorable evenings.",
    interests: ["Architectural Design", "Mixology", "Wellness Retreats", "High Fashion"],
    relationshipStatus: "COUPLE",
    lookingFor: ["Couples", "Bi Females", "Exclusive Parties"],
    isCoupleProfile: true,
    partnerDisplayName: "Sophia",
    partnerAge: 29,
    partnerGender: "FEMALE",
    showOnlineStatus: true,
    showDistance: true,
    allowDirectMessages: true,
    requireVerificationToMessage: true,
    verified: true,
    isOnline: false,
    distanceKm: 12,
    avatarUrl: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      {
        id: "m-4",
        url: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PUBLIC",
        isProfilePhoto: true,
      },
      {
        id: "m-5",
        url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PRIVATE_MEMBERS",
      },
    ],
  },
  {
    id: "prof-3",
    userId: "user-3",
    displayName: "Aria Thorne",
    age: 24,
    gender: "FEMALE",
    sexualOrientation: "PANSEXUAL",
    location: "Geneva",
    bio: "Luxury lifestyle creator & classical violinist. Monthly exclusive video journals, behind-the-scenes performances, and live streaming once a week.",
    interests: ["Classical Music", "High Jewelry", "Luxury Travel", "Photography"],
    relationshipStatus: "OPEN_RELATIONSHIP",
    lookingFor: ["Subscribers", "Mentorship", "Discreet Companionship"],
    isCoupleProfile: false,
    showOnlineStatus: true,
    showDistance: false,
    allowDirectMessages: true,
    requireVerificationToMessage: false,
    verified: true,
    isOnline: true,
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      {
        id: "m-6",
        url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PUBLIC",
        isProfilePhoto: true,
      },
      {
        id: "m-7",
        url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PAID_PER_VIEW",
        price: 49.99,
        title: "Exclusive Private Violin Session Video",
      },
    ],
  },
  {
    id: "prof-4",
    userId: "user-4",
    displayName: "Alexander Sterling",
    age: 35,
    gender: "MALE",
    sexualOrientation: "HETEROSEXUAL",
    location: "London / Mayfair",
    bio: "Venture capitalist, tech founder, and avid watch collector. Seeking a charming companion for black-tie galas and private weekend escapes.",
    interests: ["Horology", "Venture Capital", "Polo", "Fine Dining"],
    relationshipStatus: "SINGLE",
    lookingFor: ["Long-term Partner", "Gala Companion"],
    isCoupleProfile: false,
    showOnlineStatus: true,
    showDistance: true,
    allowDirectMessages: true,
    requireVerificationToMessage: true,
    verified: true,
    isOnline: false,
    distanceKm: 8,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
    coverPhotoUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      {
        id: "m-8",
        url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
        type: "IMAGE",
        visibility: "PUBLIC",
        isProfilePhoto: true,
      },
    ],
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    participant: MOCK_PROFILES[0],
    lastMessage: {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "prof-1",
      senderName: "Elena Vance",
      senderAvatar: MOCK_PROFILES[0].avatarUrl,
      content: "I'll be visiting London next Thursday. Shall we meet at the Connaught Bar?",
      createdAt: "10:42 AM",
    },
    unreadCount: 1,
    updatedAt: "10:42 AM",
  },
  {
    id: "conv-2",
    participant: MOCK_PROFILES[1],
    lastMessage: {
      id: "msg-2",
      conversationId: "conv-2",
      senderId: "user-current",
      senderName: "You",
      senderAvatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=800&q=80",
      content: "Thank you for the invitation! We would love to join your private tasting.",
      createdAt: "Yesterday",
    },
    unreadCount: 0,
    updatedAt: "Yesterday",
  },
];

export const MOCK_VERIFICATION_REQUESTS: VerificationRequest[] = [
  {
    id: "verif-101",
    user: {
      id: "usr-88",
      username: "seraphina_v",
      email: "seraphina@velora.club",
      role: "CREATOR",
    },
    idDocumentUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80",
    selfieWithNoteUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80",
    submittedAt: "2026-08-02 14:30",
    status: "PENDING",
  },
  {
    id: "verif-102",
    user: {
      id: "usr-89",
      username: "marcus_monaco",
      email: "marcus@luxury.mc",
      role: "MEMBER",
    },
    idDocumentUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=600&q=80",
    selfieWithNoteUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80",
    submittedAt: "2026-08-03 06:15",
    status: "PENDING",
  },
];

export const MOCK_REPORTS: ReportItem[] = [
  {
    id: "rep-1",
    reporterUsername: "elena_vance",
    reportedUsername: "fake_user_99",
    reportedUserRole: "MEMBER",
    reason: "UNDERAGE_SUSPICION",
    details: "User posted media that raises age verification concerns. Requesting immediate verification audit.",
    status: "PENDING",
    submittedAt: "2026-08-02 18:00",
  },
  {
    id: "rep-2",
    reporterUsername: "julian_sophia",
    reportedUsername: "spammer_bot",
    reportedUserRole: "MEMBER",
    reason: "SPAM_SOLICITATION",
    details: "Sent automated link redirecting to third-party website.",
    status: "PENDING",
    submittedAt: "2026-08-03 01:20",
  },
];
