"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import React from "react";
import { AlertTriangle, Search, Shield } from "lucide-react";
import { GodModeConsole } from "./GodModeConsole";

const NAV = [
  ["/admin", "Dashboard"], ["/admin/god", "God Mode"], ["/admin/users", "Users"], ["/admin/verification", "Verification"], ["/admin/moderation", "Moderation"], ["/admin/content", "Content"], ["/admin/reports", "Reports"], ["/admin/privacy", "Privacy & GDPR"], ["/admin/audit", "Audit Log"], ["/admin/settings", "System"], ["/admin/profile", "My Admin Profile"],
] as const;

function Panel({ title, value, detail, risk = false }: { title: string; value: React.ReactNode; detail: string; risk?: boolean }) {
  return <section className={`rounded-xl border p-4 ${risk ? "border-red-300 bg-red-50" : "border-slate-200 bg-white"}`}><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className={`mt-2 text-3xl font-bold ${risk ? "text-red-800" : "text-slate-900"}`}>{value}</p><p className="mt-1 text-xs text-slate-600">{detail}</p></section>;
}

function useAdminData(path: string) {
  const [data, setData] = React.useState<any>(null); const [error, setError] = React.useState(""); const [loading, setLoading] = React.useState(true);
  const load = React.useCallback(() => { setLoading(true); fetch(path, { credentials: "same-origin" }).then(async (r) => { const p = await r.json().catch(() => ({})); if (!r.ok) throw new Error(p.error || "Request failed"); setData(p); setError(""); }).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, [path]);
  React.useEffect(load, [load]); return { data, error, loading, load };
}

function Dashboard() {
  const { data, error, loading } = useAdminData("/api/admin/overview");
  if (loading) return <p>Loading operational state…</p>; if (error) return <p role="alert" className="text-red-700">{error}</p>;
  return <div className="space-y-6">
    <section className="rounded-xl border-2 border-red-300 bg-red-50 p-5"><div className="flex items-center gap-2"><AlertTriangle aria-hidden className="text-red-700"/><h2 className="text-lg font-bold text-red-950">Critical alerts</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Panel risk title="Critical cases" value={data.critical.count} detail={`${data.critical.unassigned} unassigned`} /><Panel risk title="Oldest case" value={`${data.critical.oldestHours}h`} detail="Target: immediate triage" /><Panel risk title="Privacy overdue" value={data.privacy.overdue} detail="Requires Privacy Admin" /></div></section>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Panel title="Open moderation" value={data.moderation.open} detail={`${data.moderation.escalated} escalated`} /><Panel title="Verification review" value={data.verification.pending + data.verification.reviewRequired} detail={`${data.verification.failed} failed`} /><Panel title="Privacy requests" value={data.privacy.open} detail={`${data.privacy.deletion} deletion`} /><Panel title="Restricted users" value={data.health.restrictedUsers} detail={`${data.health.registeredUsers} registered`} /></div>
    <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Recent admin activity</h2><div className="mt-3 divide-y">{data.recentActivity.map((event: any) => <div key={event.id} className="py-3 text-sm"><span className="font-semibold">{event.action.replaceAll("_", " ")}</span><span className="ml-2 text-slate-500">{event.resource_type} {event.resource_id}</span><p className="text-xs text-slate-500">{event.reason} · {new Date(event.created_at).toLocaleString()}</p></div>)}</div></section>
  </div>;
}

function UsersView() {
  const [query, setQuery] = React.useState(""); const [endpoint, setEndpoint] = React.useState("/api/admin/users"); const { data, error, loading } = useAdminData(endpoint);
  const act = async (id: string, action: string) => { const reason = window.prompt(`${action} reason (required)`)?.trim(); if (!reason) return; const category = window.prompt("Decision category")?.trim(); if (!category) return; const high = ["SUSPEND","BAN","REACTIVATE"].includes(action); const response = await fetch(`/api/admin/users/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, reason, category, confirmation: high ? `CONFIRM ${action}` : undefined }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) alert(payload.error || "Action failed"); else setEndpoint(`/api/admin/users?q=${encodeURIComponent(query)}&refresh=${Date.now()}`); };
  return <div className="space-y-4"><form onSubmit={(e) => { e.preventDefault(); setEndpoint(`/api/admin/users?q=${encodeURIComponent(query)}`); }} className="flex gap-2"><label className="sr-only" htmlFor="admin-search">Search users</label><input id="admin-search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Username, email, Auth0 or internal ID" className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2"/><button className="rounded-lg bg-slate-900 px-4 py-2 text-white"><Search className="inline h-4 w-4"/> Search</button></form>{loading ? <p>Loading users…</p> : error ? <p role="alert" className="text-red-700">{error}</p> : <div className="overflow-x-auto rounded-xl border bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-100"><tr>{["User","Status","Trust","Location","Created","Actions"].map((h) => <th scope="col" className="p-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{data.users.map((u: any) => <tr key={u.id}><td className="p-3"><strong>{u.display_name || u.username || "Unnamed"}</strong><p className="text-xs text-slate-500">{u.email}</p><p className="font-mono text-[10px] text-slate-400">{u.id}</p></td><td className="p-3">{u.account_status}</td><td className="p-3">{u.age_verification_status}<br/>{u.verification_status}</td><td className="p-3">{[u.city,u.country].filter(Boolean).join(", ")}</td><td className="p-3">{new Date(u.created_at).toLocaleDateString()}</td><td className="p-3"><div className="flex flex-wrap gap-1">{["WARN","RESTRICT","SUSPEND","BAN","REACTIVATE"].map((a) => <button key={a} onClick={() => act(u.id,a)} className="rounded border px-2 py-1 text-xs focus:ring-2 focus:ring-blue-600">{a}</button>)}</div></td></tr>)}</tbody></table></div>}</div>;
}

function QueueView({ kind }: { kind: "moderation" | "privacy" | "verification" | "audit" }) {
  const endpoint = kind === "moderation" ? "/api/admin/moderation" : `/api/admin/${kind}`; const { data, error, loading, load } = useAdminData(endpoint); const rows = data?.cases || data?.requests || data?.reviews || data?.events || [];
  const update = async (row: any) => { const status = window.prompt("New status/decision")?.trim(); const reason = window.prompt("Reason (required and auditable)")?.trim(); if (!status || !reason) return; const body = kind === "moderation" ? { id: row.id, status, decision: status, decisionReason: reason } : { id: row.id, status, reason }; const r = await fetch(endpoint, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const p = await r.json().catch(() => ({})); if (!r.ok) alert(p.error || "Update failed"); else load(); };
  return loading ? <p>Loading queue…</p> : error ? <p role="alert" className="text-red-700">{error}</p> : <div className="space-y-3">{rows.length === 0 && <p className="rounded-xl border bg-white p-5">No items in this queue.</p>}{rows.map((row: any) => <article key={row.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="font-mono text-xs text-slate-500">{row.id}</span><h2 className="font-bold">{row.reason || row.request_type || row.verification_type || row.action}</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{row.priority || row.status}</span></div><p className="mt-2 text-sm text-slate-600">{row.description || row.notes || row.resource_type || "Operational record"}</p>{kind !== "audit" && <button onClick={() => update(row)} className="mt-3 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white">Review / update</button>}</article>)}</div>;
}

function SettingsView() { const { data, error, loading, load } = useAdminData("/api/admin/settings"); const toggle = async (f: any) => { const reason = window.prompt("Reason for feature flag change")?.trim(); if (!reason) return; const r = await fetch("/api/admin/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key: f.flag_key, enabled: !f.enabled, reason, confirmation: `CONFIRM ${f.flag_key}` }) }); const p = await r.json().catch(() => ({})); if (!r.ok) alert(p.error || "Change failed"); else load(); }; return loading ? <p>Loading settings…</p> : error ? <p role="alert" className="text-red-700">{error}</p> : <div className="space-y-3">{data.flags.map((f: any) => <div key={f.flag_key} className="flex items-center justify-between rounded-xl border bg-white p-4"><div><strong>{f.flag_key}</strong><p className="text-xs text-slate-500">{f.description}</p></div><button disabled={f.flag_key === "MONETIZATION_ENABLED"} onClick={() => toggle(f)} className="rounded border px-3 py-2 disabled:cursor-not-allowed disabled:opacity-50">{f.enabled ? "Enabled" : "Disabled"}</button></div>)}</div>; }

export function AdminCommandCenter({ actor }: { actor: { role: string; email: string; mfaAuthenticated: boolean } }) {
  const pathname = usePathname(); let content: React.ReactNode = <Dashboard/>; let title = "Operational dashboard";
  if (pathname.startsWith("/admin/god")) { title = "God Mode control center"; content = <GodModeConsole/>; }
  if (pathname.startsWith("/admin/users")) { title = "User management"; content = <UsersView/>; } else if (pathname.startsWith("/admin/moderation") || pathname.startsWith("/admin/reports")) { title = "Moderation center"; content = <QueueView kind="moderation"/>; } else if (pathname.startsWith("/admin/privacy")) { title = "Privacy & GDPR"; content = <QueueView kind="privacy"/>; } else if (pathname.startsWith("/admin/verification")) { title = "Verification & age assurance"; content = <QueueView kind="verification"/>; } else if (pathname.startsWith("/admin/audit")) { title = "Immutable admin activity"; content = <QueueView kind="audit"/>; } else if (pathname.startsWith("/admin/settings")) { title = "System settings"; content = <SettingsView/>; } else if (pathname.startsWith("/admin/profile")) { title = "My admin profile"; content = <div className="rounded-xl border bg-white p-5"><dl className="grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Email</dt><dd>{actor.email}</dd></div><div><dt className="text-xs text-slate-500">Role</dt><dd>{actor.role}</dd></div><div><dt className="text-xs text-slate-500">MFA claim</dt><dd>{actor.mfaAuthenticated ? "Verified in session" : "Required in production"}</dd></div><div><dt className="text-xs text-slate-500">Role changes</dt><dd>Cannot be changed by this account</dd></div></dl></div>; } else if (pathname.startsWith("/admin/content")) { title = "Content moderation"; content = <QueueView kind="moderation"/>; }
  return <div className="min-h-screen bg-slate-100 text-slate-950"><header className="border-b bg-slate-950 text-white"><div className="mx-auto flex max-w-[1600px] items-center justify-between px-4 py-3"><div className="flex items-center gap-3"><Shield aria-hidden/><div><p className="font-bold">Intimo Operations</p><p className="text-xs text-slate-300">Trust · Safety · Privacy</p></div></div><div className="text-right text-xs"><p>{actor.email}</p><p className="text-slate-300">{actor.role.replaceAll("_", " ")}</p></div></div></header><div className="mx-auto grid max-w-[1600px] lg:grid-cols-[240px_1fr]"><nav aria-label="Admin" className="border-r bg-white p-3 lg:min-h-[calc(100vh-65px)]"><ul className="grid grid-cols-2 gap-1 sm:grid-cols-3 lg:grid-cols-1">{NAV.map(([href,label]) => <li key={href}><Link href={href} className={`block rounded-lg px-3 py-2 text-sm font-medium focus:ring-2 focus:ring-blue-600 ${pathname === href ? "bg-slate-900 text-white" : "hover:bg-slate-100"}`}>{label}</Link></li>)}</ul></nav><main className="min-w-0 p-4 sm:p-6"><div className="mb-5"><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-sm text-slate-600">Actionable operational information. Sensitive access and decisions are audited.</p></div>{content}</main></div></div>;
}
