"use client";
import React from "react";
type MediaItem={id:string;owner_id:string;media_type:string;mime_type:string;byte_size:number;visibility:string;upload_status:string;processing_status:string;moderation_status:string;title?:string|null;description?:string|null;created_at:string};
type AlbumItem={id:string;owner_id:string;title:string;description?:string|null;visibility:string;moderation_status:string;photo_count:number;created_at:string};
const decisions=["UNDER_REVIEW","APPROVED","HIDDEN","REJECTED","REMOVED"] as const;
function label(decision:string,type:"media"|"album"){if(decision==="UNDER_REVIEW")return"Start review";if(decision==="APPROVED")return type==="album"?"Approve album":"Approve and publish";if(decision==="HIDDEN")return"Hide";if(decision==="REJECTED")return"Reject";return"Remove";}
export function AdminMediaConsole(){const[items,setItems]=React.useState<MediaItem[]>([]);const[albums,setAlbums]=React.useState<AlbumItem[]>([]);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState("");const[reasonById,setReasonById]=React.useState<Record<string,string>>({});
const load=React.useCallback(()=>{setLoading(true);Promise.all([fetch("/api/admin/media",{credentials:"same-origin"}),fetch("/api/admin/albums",{credentials:"same-origin"})]).then(async([mr,ar])=>{const mp=await mr.json().catch(()=>({}));const ap=await ar.json().catch(()=>({}));if(!mr.ok)throw new Error(mp.error||"Content queue unavailable");if(!ar.ok)throw new Error(ap.error||"Album queue unavailable");setItems(mp.media||[]);setAlbums(ap.albums||[]);setError("");}).catch(cause=>setError(cause.message||"Content queue unavailable")).finally(()=>setLoading(false));},[]);React.useEffect(load,[load]);
async function decide(type:"media"|"album",id:string,decision:string){const key=`${type}:${id}`;const reason=(reasonById[key]||"").trim();if(reason.length<10){setError("Enter a specific reason of at least 10 characters before deciding.");return;}const destructive=decision==="REJECTED"||decision==="REMOVED";const response=await fetch(type==="album"?"/api/admin/albums":"/api/admin/media",{method:"PATCH",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,decision,reason,confirmation:destructive?`CONFIRM ${decision}`:undefined})});const payload=await response.json().catch(()=>({}));if(!response.ok){setError(payload.error||"Decision failed");return;}setError("");load();}
function controls(type:"media"|"album",id:string){const key=`${type}:${id}`;return <><label className="mt-4 block text-xs font-semibold" htmlFor={`reason-${key}`}>Auditable decision reason</label><textarea id={`reason-${key}`} value={reasonById[key]||""} onChange={event=>setReasonById(current=>({...current,[key]:event.target.value}))} className="mt-1 min-h-20 w-full rounded-lg border border-slate-300 p-2 text-sm" placeholder="State the policy basis and relevant evidence. Do not include unnecessary identity data."/><div className="mt-3 flex flex-wrap gap-2">{decisions.map(decision=><button key={decision} onClick={()=>decide(type,id,decision)} className={`rounded-lg px-3 py-2 text-xs font-bold ${decision==="APPROVED"?"bg-emerald-700 text-white":decision==="HIDDEN"?"bg-amber-600 text-white":["REJECTED","REMOVED"].includes(decision)?"border border-red-700 text-red-800":"border"}`}>{label(decision,type)}</button>)}</div></>}
if(loading)return<p>Loading durable content queue…</p>;return <div className="space-y-4">{error&&<p role="alert" className="rounded-lg border border-red-300 bg-red-50 p-3 text-sm text-red-800">{error}</p>}{items.length===0&&albums.length===0&&<p className="rounded-xl border bg-white p-5">No uploaded media or albums exist.</p>}{albums.map(item=><article key={`album:${item.id}`} className="rounded-xl border border-amber-300 bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-amber-700">Album · {item.photo_count} photos</p><h2 className="font-bold">{item.title}</h2><p className="text-sm text-slate-600">{item.description||"No description supplied."}</p><p className="mt-2 font-mono text-[11px] text-slate-500">Album {item.id} · Owner {item.owner_id}</p></div><div className="text-right text-xs"><strong>{item.moderation_status}</strong><p>{item.visibility}</p></div></div>{controls("album",item.id)}</article>)}{items.map(item=><article key={item.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{item.media_type} · {item.mime_type} · {Math.ceil(item.byte_size/1024)} KB</p><h2 className="mt-1 font-bold">{item.title||"Untitled media"}</h2><p className="mt-1 max-w-2xl text-sm text-slate-600">{item.description||"No description supplied."}</p><p className="mt-2 font-mono text-[11px] text-slate-500">Media {item.id} · Owner {item.owner_id}</p></div><div className="text-right text-xs"><strong>{item.moderation_status}</strong><p>{item.upload_status} · {item.processing_status}</p><p>{item.visibility}</p></div></div>{controls("media",item.id)}</article>)}</div>}
