"use client";
import React from "react";
import { AlertTriangle, Crown, LogOut, ShieldAlert } from "lucide-react";
export function GodModeConsole() {
  const [active,setActive]=React.useState<boolean|null>(null); const [data,setData]=React.useState<any>(null); const [error,setError]=React.useState("");
  const load=React.useCallback(async()=>{const session=await fetch("/api/admin/god/session");if(!session.ok){setActive(false);return;}setActive(true);const response=await fetch("/api/admin/god/overview");const payload=await response.json().catch(()=>({}));if(!response.ok)setError(payload.error||"God Mode overview unavailable");else setData(payload);},[]); React.useEffect(()=>{load();},[load]);
  const enter=async()=>{const reason=window.prompt("Operational reason for entering God Mode")?.trim();if(!reason)return;const confirmation=window.prompt('Type "ENTER GOD MODE"')?.trim();const mfaCode=window.prompt("Enter the current six-digit code from your authenticator app")?.trim();const response=await fetch("/api/admin/god/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason,confirmation,mfaCode})});const payload=await response.json().catch(()=>({}));if(!response.ok)setError(payload.error||"Elevation failed");else load();};
  const exit=async()=>{await fetch("/api/admin/god/session",{method:"DELETE"});setData(null);setActive(false);};
  if(active===null)return <p>Checking elevation…</p>; if(!active)return <section className="mx-auto max-w-xl rounded-2xl border-2 border-amber-400 bg-white p-7"><Crown className="h-10 w-10 text-amber-600"/><h2 className="mt-4 text-2xl font-bold">Enter God Mode</h2><p className="mt-2 text-sm text-slate-600">Requires SUPER_ADMIN, verified email, MFA and authentication within five minutes.</p><div role="alert" className="mt-4 rounded-lg bg-amber-50 p-3 text-sm font-semibold text-amber-950">You are entering God Mode. All actions are audited.</div>{error&&<p className="mt-3 text-red-700">{error}</p>}<button onClick={enter} className="mt-5 rounded-lg bg-amber-600 px-4 py-3 font-bold text-white">Authenticate intent and enter</button></section>; if(error||!data)return <p role="alert" className="text-red-700">{error||"Loading elevated operations…"}</p>;
  return <div className="space-y-5"><div className="sticky top-2 z-20 flex items-center justify-between rounded-xl border-2 border-red-500 bg-red-950 p-4 text-white shadow-xl"><div className="flex items-center gap-3"><ShieldAlert/><div><strong>GOD MODE ACTIVE</strong><p className="text-xs text-red-200">Short-lived elevation · all actions audited</p></div></div><button onClick={exit} className="rounded border border-white/40 px-3 py-2 text-sm"><LogOut className="inline h-4 w-4"/> Exit</button></div><section className="rounded-xl border-2 border-red-300 bg-red-50 p-5"><h2 className="flex items-center gap-2 font-bold text-red-950"><AlertTriangle/>Critical incidents</h2><p className="mt-3 text-4xl font-bold text-red-800">{data.criticalIncidents.length}</p></section><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{[["Users",data.platform.users],["Moderation backlog",data.platform.moderationBacklog],["Restricted/suspended",data.userOperations.restricted+data.userOperations.suspended],["Open privacy",data.privacy.open],["Content hidden",data.content.hidden],["Content removed",data.content.removed],["Active admins",data.admins.filter((a:any)=>a.status==="ACTIVE").length],["Deletion pending",data.userOperations.deletionPending]].map(([label,value])=><section key={String(label)} className="rounded-xl border bg-white p-4"><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></section>)}</div><section className="rounded-xl border bg-white p-5"><h2 className="font-bold">System control state</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{data.flags.map((f:any)=><div key={f.flag_key} className="flex justify-between rounded border p-3 text-sm"><span>{f.flag_key}</span><strong>{f.enabled?"ENABLED":"DISABLED"}</strong></div>)}</div></section></div>;
}
