import { NextRequest, NextResponse } from "next/server";
import { requireGodMode } from "@/lib/auth/godMode";
import { getServerSupabase } from "@/lib/supabase/server";
export async function GET(req: NextRequest) {
  const god = await requireGodMode(req); if (!("elevatedSessionId" in god)) return god.response;
  const db = getServerSupabase(); if (!db) return NextResponse.json({ error: "God Mode data unavailable" }, { status: 503 });
  const [profiles, cases, privacy, media, flags, admins, actions] = await Promise.all([
    db.from("profiles").select("id,account_status,created_at,last_active_at,age_verification_status").limit(2000), db.from("moderation_cases").select("id,status,priority,reason,created_at").neq("status","RESOLVED").neq("status","REJECTED").limit(500), db.from("privacy_requests").select("id,request_type,status,due_at").neq("status","COMPLETED").limit(500), db.from("media_objects").select("id,moderation_status").limit(2000), db.from("system_feature_flags").select("flag_key,enabled,description,updated_at").order("flag_key"), db.from("admin_assignments").select("id,profile_id,role,status,granted_at").order("granted_at", { ascending: false }), db.from("admin_action_events").select("id,actor_role,action,resource_type,resource_id,reason,created_at").order("created_at", { ascending: false }).limit(20),
  ]);
  if ([profiles,cases,privacy,media,flags,admins,actions].some((r) => r.error)) return NextResponse.json({ error: "God Mode overview failed" }, { status: 502 });
  const p = profiles.data || []; const c = cases.data || []; const pr = privacy.data || []; const m = media.data || [];
  return NextResponse.json({ elevatedSessionId: god.elevatedSessionId, criticalIncidents: c.filter((x) => x.priority === "CRITICAL"), platform: { users: p.length, newUsers7d: p.filter((x) => Date.now() - new Date(x.created_at).getTime() < 604800000).length, verificationReview: p.filter((x) => ["FAILED","REVIEW_REQUIRED"].includes(x.age_verification_status)).length, moderationBacklog: c.length }, userOperations: { restricted: p.filter((x) => x.account_status === "RESTRICTED").length, suspended: p.filter((x) => x.account_status === "SUSPENDED").length, banned: p.filter((x) => x.account_status === "BANNED").length, deletionPending: p.filter((x) => x.account_status === "DELETION_REQUESTED").length }, content: { underReview: m.filter((x) => x.moderation_status === "UNDER_REVIEW").length, hidden: m.filter((x) => x.moderation_status === "HIDDEN").length, removed: m.filter((x) => x.moderation_status === "REMOVED").length }, privacy: { open: pr.length, deletion: pr.filter((x) => x.request_type === "DELETION").length, export: pr.filter((x) => x.request_type === "EXPORT").length }, flags: flags.data || [], admins: admins.data || [], recentActions: actions.data || [] }, { headers: { "Cache-Control": "private, no-store" } });
}
