"use client";

import React from "react";
import Link from "next/link";
import { Bell, Heart, MessageSquare, ShieldCheck, UserPlus, X, Trash2 } from "lucide-react";
import { useDurableNotifications } from "@/lib/notifications/useDurableNotifications";

export const NotificationDrawer: React.FC<{ isOpen: boolean; onClose: () => void; onUnreadChange?: (count: number) => void }> = ({ isOpen, onClose, onUnreadChange }) => {
  const state = useDurableNotifications(isOpen);
  React.useEffect(() => { onUnreadChange?.(state.unreadCount); }, [onUnreadChange, state.unreadCount]);
  if (!isOpen) return null;
  const icon = (type: string) => type === "NEW_MESSAGE" ? <MessageSquare className="h-4 w-4 text-amber-300" /> : type === "FAVORITED" ? <Heart className="h-4 w-4 text-rose-400" /> : type === "NEW_FOLLOWER" ? <UserPlus className="h-4 w-4 text-sky-400" /> : <ShieldCheck className="h-4 w-4 text-emerald-400" />;
  return <div className="absolute right-0 top-14 z-50 w-80 rounded-2xl border border-amber-300/30 bg-[#11151e] p-4 text-left shadow-2xl sm:w-96"><div className="flex items-center justify-between border-b border-white/10 pb-3"><div className="flex items-center gap-2"><Bell className="h-4 w-4 text-amber-300" /><h2 className="text-sm font-bold text-white">Notifications</h2>{state.unreadCount > 0 && <span className="rounded-full bg-amber-300 px-2 py-0.5 text-[10px] font-bold text-black">{state.unreadCount} new</span>}</div><button onClick={onClose} aria-label="Close notifications" className="p-1 text-slate-400 hover:text-white"><X className="h-4 w-4" /></button></div><div className="mt-3 flex gap-3 text-[11px] font-semibold">{state.unreadCount > 0 && <button onClick={() => state.markAllRead().catch(() => {})} className="text-amber-300">Mark all read</button>}{state.notifications.length > 0 && <button onClick={() => state.clear().catch(() => {})} className="text-red-400">Delete all</button>}</div><div className="mt-3 max-h-96 space-y-2 overflow-y-auto">{state.loading ? <p className="py-8 text-center text-xs text-slate-400">Loading…</p> : state.error ? <p role="alert" className="py-5 text-xs text-red-400">{state.error}</p> : state.notifications.length === 0 ? <p className="py-8 text-center text-xs text-slate-400">No notifications.</p> : state.notifications.map((item) => <div key={item.id} className={`relative rounded-xl border ${item.isRead ? "border-white/5 bg-white/[0.02]" : "border-amber-300/30 bg-amber-300/5"}`}><Link href={item.targetLink || "/notifications"} onClick={() => { if (!item.isRead) state.markRead(item.id).catch(() => {}); onClose(); }} className="flex gap-3 p-3 pr-9"><div className="mt-0.5">{icon(item.type)}</div><div className="min-w-0"><p className="truncate text-xs font-bold text-white">{item.title}</p><p className="mt-1 line-clamp-2 text-[11px] text-slate-400">{item.message}</p><time className="mt-1 block text-[10px] text-slate-600">{new Date(item.createdAt).toLocaleString()}</time></div></Link><button onClick={() => state.remove(item.id).catch(() => {})} aria-label="Delete notification" className="absolute right-2 top-2 p-1 text-slate-500 hover:text-red-400"><Trash2 className="h-3.5 w-3.5" /></button></div>)}</div><Link href="/notifications" onClick={onClose} className="mt-3 block border-t border-white/10 pt-3 text-center text-xs font-bold text-amber-300">View all notifications</Link></div>;
};
