"use client";

import Link from "next/link";
import { Bell, Trash2 } from "lucide-react";
import { useDurableNotifications } from "@/lib/notifications/useDurableNotifications";

export default function NotificationsPage() {
  const state = useDurableNotifications();
  return <main className="mx-auto max-w-4xl space-y-6 px-4 py-8 sm:px-6"><div className="flex flex-col gap-4 border-b border-white/10 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="flex items-center gap-3 font-serif text-3xl font-bold text-white"><Bell className="h-7 w-7 text-amber-300" />Notifications</h1><p className="mt-2 text-sm text-slate-400">Real account, interaction, moderation, and messaging events across devices.</p></div><div className="flex gap-2">{state.unreadCount > 0 && <button onClick={() => state.markAllRead().catch(() => {})} className="min-h-11 rounded-lg border border-white/10 px-4 text-sm font-semibold text-white">Mark all read</button>}{state.notifications.length > 0 && <button onClick={() => state.clear().catch(() => {})} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-red-400/30 px-4 text-sm font-semibold text-red-300"><Trash2 className="h-4 w-4" />Delete all</button>}</div></div>{state.loading ? <p className="text-sm text-slate-400">Loading notifications…</p> : state.error ? <p role="alert" className="rounded-lg border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-300">{state.error}</p> : state.notifications.length === 0 ? <div className="rounded-xl border border-dashed border-white/15 p-10 text-center"><Bell className="mx-auto h-7 w-7 text-slate-500" /><h2 className="mt-3 font-semibold text-white">No notifications yet</h2><p className="mt-1 text-sm text-slate-400">New messages, follows, moderation outcomes, and verification updates will appear here.</p></div> : <div className="space-y-3">{state.notifications.map((item) => <article key={item.id} className={`rounded-xl border p-4 ${item.isRead ? "border-white/10 bg-[#11151e]" : "border-amber-300/30 bg-amber-300/5"}`}><div className="flex items-start justify-between gap-4"><Link href={item.targetLink || "#"} onClick={() => { if (!item.isRead) state.markRead(item.id).catch(() => {}); }} className="min-w-0"><div className="flex items-center gap-2"><h2 className="font-semibold text-white">{item.title}</h2>{!item.isRead && <span className="rounded-full bg-amber-300 px-2 py-0.5 text-[10px] font-bold text-black">Unread</span>}</div><p className="mt-2 text-sm text-slate-300">{item.message}</p><time className="mt-2 block text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</time></Link><button onClick={() => state.remove(item.id).catch(() => {})} aria-label="Delete notification" className="p-2 text-slate-500 hover:text-red-400"><Trash2 className="h-4 w-4" /></button></div></article>)}</div>}</main>;
}
